# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{voomify_email_integrator}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Russell Edens"]
  s.date = %q{2010-10-05}
  s.description = %q{This gem contains the logic for reading email from a pop3 mailbox}
  s.email = %q{russell@voomify.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/email_integrator.rb",
     "lib/email_integrator/email_integrator.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://www.github.com/voomify/email_integrator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Voomify email integrator. Reads POP3 emails.}
  s.test_files = [
    "spec/email_integrator_spec.rb",
     "spec/support/exception_helper.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

